repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy ./bbpp --ignore-missing-imports
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
      - id: blue
        name: blue
        language: system
        entry: blue --check . --diff
        types: [ python ]
        always_run: true
        pass_filenames: false
      - id: bandit
        name: bandit
        language: system
        entry: bandit -r ./bbpp
        types: [ python ]
        always_run: true
        pass_filenames: false